file=open("demo.txt","r")
str1=file.read()
file.close()
file=open("demo1.txt","w")
file.write(str1)
file.close()
file=open("demo1.txt","r")
print("second file -->\n",file.read())
file.close()
